version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:8.0'
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          name: Run Pact Broker
          command: docker-compose up
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
      - run:
          name: Run Pact Broker
          command: docker-compose down

executors:
  j8:
    docker:
      - image: 'cimg/openjdk:8.0'

orbs:
  maven: circleci/maven@1.4.0
  docker: circleci/docker@2.2.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j8
      - build:
          context: SonarCloud