pipeline {
    agent any
    tools {
        maven 'M3'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/piomin/sample-testing-microservices.git', credentialsId: 'github-piomin', branch: 'master'
            }
        }
        stage('Tests') {
            steps {
                dir('performance-tests') {
                    sh 'mvn clean package gatling:execute'
                }
            }
        }
    }
    post {
        always {
            gatlingArchive()
        }
    }
}