pipeline {
    agent any
    tools {
        maven 'M3'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/piomin/sample-testing-microservices.git', credentialsId: 'github-piomin', branch: 'master'
            }
        }
        stage('Tests') {
            steps {
                dir('trip-management') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('Integration Tests') {
            steps {
                dir('trip-management') {
                    sh 'mvn clean verify -P integration-test, !unit-tests'
                }
            }
        }
        stage('Build') {
            steps {
                dir('trip-management') {
                    sh 'mvn package -Dmaven.test.skip=true'
                }
            }
        }
    }
    post {
        always {
            junit '**/target/*.xml'
        }
    }
}