pipeline {
    agent any
    tools {
        maven 'M3'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/piomin/sample-testing-microservices.git', credentialsId: 'github-piomin', branch: 'master'
            }
        }
        stage('Tests') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Integration Tests') {
            steps {
                sh 'mvn verify'
            }
            unstable {
                input {
                    message: 'Continue?'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn package -Dmaven.test.skip=true'
            }
        }
    }
    post {
        always {
            junit '**/target/*.xml'
        }
    }
}